# Generated by Django 2.1.7 on 2019-07-28 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(blank=True, max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('orderer', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=800)),
                ('phone1', models.CharField(max_length=100)),
                ('phone2', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('price', models.IntegerField()),
                ('delivery', models.IntegerField(null=True)),
                ('total_price', models.IntegerField()),
            ],
        ),
    ]
