# Generated by Django 2.1.7 on 2019-07-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190730_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
